spring:
    profiles:
        active:
        - dev
---
server:
    port: 8201
spring:
    profiles: dev
    application:
        name: springcloud-config-huihui-dev
eureka:
    client:
        service-url:
            defaultZone: http://eureka-dev.com:7001/eureka/
---
server:
    port: 8202
spring:
    profiles: test
    application:
        name: springcloud-config-huihui-test
eureka:
    client:
        service-url:
            defaultZone: http://eureka-dev.com:7001/eureka/